-- Generated by nwg-displays on 2026-07-06 at 21:17:45. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "1920x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-1",
    disabled = true
})
