-- Generated by nwg-displays on 2026-05-20 at 17:50:28. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-1",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1",
    default = true
})
